version: "3"
services:
  kmb-react:
    image: kmb-react-prod:${ENV}
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy-data:/data
      - caddy-config:/config
    networks:
      - kmb-app
  kmb-server:
    image: kmb-server
    restart: unless-stopped
    env_file:
      - ./server/config/${ENV}.env
    ports:
      - "8080:8080"
    networks:
      - kmb-app
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - '9090:9090'
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

#  grafana:
#    image: grafana/grafana:latest
#    container_name: grafane
#    ports:
#      - "5000:5000"
#    volumes:
#      - grafana-data:/var/lib/grafana
#    restart: unless-stopped

networks:
  kmb-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
  caddy-data:
    driver: local
  caddy-config:
    driver: local
  prometheus.yml:
    driver: local

