export const QUIZ_CATEGORY_LIST_REQUEST = "QUIZ_CATEGORY_LIST_REQUEST"
export const QUIZ_CATEGORY_LIST_SUCCESS = "QUIZ_CATEGORY_LIST_SUCCESS"
export const QUIZ_CATEGORY_LIST_FAIL = "QUIZ_CATEGORY_LIST_FAIL"

export const QUIZ_SUBCATEGORY_LIST_REQUEST = "QUIZ_SUBCATEGORY_LIST_REQUEST"
export const QUIZ_SUBCATEGORY_LIST_SUCCESS = "QUIZ_SUBCATEGORY_LIST_SUCCESS"
export const QUIZ_SUBCATEGORY_LIST_FAIL = "QUIZ_SUBCATEGORY_LIST_FAIL"

export const QUIZ_LIST_REQUEST = "QUIZ_LIST_REQUEST"
export const QUIZ_LIST_SUCCESS = "QUIZ_LIST_SUCCESS"
export const QUIZ_LIST_FAIL = "QUIZ_LIST_FAIL"

export const QUIZ_UPDATE_REQUEST = "QUIZ_UPDATE_REQUEST"
export const QUIZ_UPDATE_SUCCESS = "QUIZ_UPDATE_SUCCESS"
export const QUIZ_UPDATE_FAIL = "QUIZ_UPDATE_FAIL"

export const QUIZ_INDEX_INCREMENT_REQUEST = "QUIZ_INDEX_INCREMENT_REQUEST"
export const QUIZ_INDEX_INCREMENT_SUCCESS = "QUIZ_INDEX_INCREMENT_SUCCESS"
export const QUIZ_INDEX_INCREMENT_FAIL = "QUIZ_INDEX_INCREMENT_FAIL"

export const QUIZ_ANSWER_SELECTED = "QUIZ_ANSWER_SELECTED"
export const QUIZ_ANSWER_DESELECTED = "QUIZ_ANSWER_DESELECTED"