export const QUIZ_CATEGORY_LIST_REQUEST = "QUIZ_CATEGORY_LIST_REQUEST"
export const QUIZ_CATEGORY_LIST_SUCCESS = "QUIZ_CATEGORY_LIST_SUCCESS"
export const QUIZ_CATEGORY_LIST_FAIL = "QUIZ_CATEGORY_LIST_FAIL"

export const QUIZ_LIST_REQUEST = "QUIZ_LIST_REQUEST"
export const QUIZ_LIST_SUCCESS = "QUIZ_LIST_SUCCESS"
export const QUIZ_LIST_FAIL = "QUIZ_LIST_FAIL"

export const CURRENT_QUIZ_UPDATE_REQUEST = "CURRENT_QUIZ_UPDATE_REQUEST"
export const CURRENT_QUIZ_UPDATE_SUCCESS = "CURRENT_QUIZ_UPDATE_SUCCESS"
export const CURRENT_QUIZ_UPDATE_FAIL = "CURRENT_QUIZ_UPDATE_FAIL"

export const QUIZ_ANSWER_SELECTED_REQUEST = "QUIZ_ANSWER_SELECTED_REQUEST"
export const QUIZ_ANSWER_SELECTED_SUCCESS = "QUIZ_ANSWER_SELECTED_SUCCESS"
export const QUIZ_ANSWER_SELECTED_FAIL = "QUIZ_ANSWER_SELECTED_FAIL"