export const SCORE_UPDATE_REQUEST = "SCORE_UPDATE_REQUEST";
export const SCORE_UPDATE_SUCCESS = "SCORE_UPDATE_SUCCESS";
export const SCORE_UPDATE_FAIL = "SCORE_UPDATE_FAIL";

export const SCORE_RESET = "SCORE_RESET";

export const SCORE_SHOW = "SCORE_SHOW";
export const SCORE_HIDE = "SCORE_HIDE";