export const SCORE_UPDATE_REQUEST = "SCORE_UPDATE_REQUEST"
export const SCORE_UPDATE_SUCCESS = "SCORE_UPDATE_SUCCESS"
export const SCORE_UPDATE_FAIL = "SCORE_UPDATE_FAIL"

export const SCORE_SHOW_REQUEST = "SCORE_SHOW_REQUEST"
export const SCORE_SHOW_SUCCESS = "SCORE_SHOW_SUCCESS"
export const SCORE_SHOW_FAIL = "SCORE_SHOW_FAIL"